AWSTemplateFormatVersion: '2010-09-09'
Description: 'Phoenix - Database Stack (RDS PostgreSQL Multi-AZ)'

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
  VpcId:
    Type: String
  DataSubnetIds:
    Type: CommaDelimitedList
  DBSecurityGroupId:
    Type: String
  DBInstanceClass:
    Type: String
  DBAllocatedStorage:
    Type: Number

Resources:
  #============================================================================
  # DB Subnet Group
  #============================================================================
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Phoenix PostgreSQL
      SubnetIds: !Ref DataSubnetIds
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-db-subnet-group'

  #============================================================================
  # Secrets Manager - Database Credentials
  #============================================================================
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/database-credentials'
      Description: Phoenix PostgreSQL database credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "phoenix_admin"}'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  #============================================================================
  # RDS Parameter Group
  #============================================================================
  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Family: postgres16
      Description: Phoenix PostgreSQL parameter group
      Parameters:
        log_statement: all
        log_min_duration_statement: 1000
        shared_preload_libraries: pg_stat_statements
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-db-params'

  #============================================================================
  # RDS Instance
  #============================================================================
  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub '${ProjectName}-${Environment}'
      DBInstanceClass: !Ref DBInstanceClass
      Engine: postgres
      EngineVersion: '16.4'
      AllocatedStorage: !Ref DBAllocatedStorage
      MaxAllocatedStorage: 1000
      StorageType: gp3
      StorageEncrypted: true
      MultiAZ: true
      DBName: phoenix
      MasterUsername: !Sub '{{resolve:secretsmanager:${DBSecret}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBSecret}:SecretString:password}}'
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroupId
      DBParameterGroupName: !Ref DBParameterGroup
      BackupRetentionPeriod: 14
      PreferredBackupWindow: '03:00-04:00'
      PreferredMaintenanceWindow: 'sun:04:00-sun:05:00'
      EnablePerformanceInsights: true
      PerformanceInsightsRetentionPeriod: 7
      MonitoringInterval: 60
      MonitoringRoleArn: !GetAtt RDSMonitoringRole.Arn
      EnableCloudwatchLogsExports:
        - postgresql
        - upgrade
      DeletionProtection: true
      CopyTagsToSnapshot: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-db'
        - Key: Environment
          Value: !Ref Environment

  #============================================================================
  # RDS Enhanced Monitoring Role
  #============================================================================
  RDSMonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-rds-monitoring'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole

  #============================================================================
  # Secret with Connection String
  #============================================================================
  DBConnectionSecret:
    Type: AWS::SecretsManager::Secret
    DependsOn: DBInstance
    Properties:
      Name: !Sub '${ProjectName}/database-url'
      Description: Phoenix PostgreSQL connection URL
      SecretString: !Sub
        - 'postgresql://${Username}:${Password}@${Endpoint}:5432/phoenix'
        - Username: !Sub '{{resolve:secretsmanager:${DBSecret}:SecretString:username}}'
          Password: !Sub '{{resolve:secretsmanager:${DBSecret}:SecretString:password}}'
          Endpoint: !GetAtt DBInstance.Endpoint.Address
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  #============================================================================
  # CloudWatch Alarms
  #============================================================================
  DBCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-${Environment}-db-cpu-high'
      AlarmDescription: Database CPU utilization high
      MetricName: CPUUtilization
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstance

  DBStorageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-${Environment}-db-storage-low'
      AlarmDescription: Database free storage space low
      MetricName: FreeStorageSpace
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      Threshold: 10737418240  # 10 GB
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstance

  DBConnectionsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-${Environment}-db-connections-high'
      AlarmDescription: Database connections high
      MetricName: DatabaseConnections
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstance

Outputs:
  DBEndpoint:
    Description: Database endpoint
    Value: !GetAtt DBInstance.Endpoint.Address

  DBPort:
    Description: Database port
    Value: !GetAtt DBInstance.Endpoint.Port

  DBSecretArn:
    Description: Database connection string secret ARN
    Value: !Ref DBConnectionSecret

  DBInstanceId:
    Description: Database instance identifier
    Value: !Ref DBInstance
